### ISSUE TITLE
Web Author Impose Ditamap Plugin Hides Connection Options on Dashboard in v26

### ISSUE THREAD

**Issue by reifsnid** [oxygenxml/web-author-sample-plugins#6]
We recently upgraded our Web Author instance to v26. However, we've noticed that the Web Author Impose Ditamap plugin hides all of the connection options on the Dashboard (Git, GitHub, Perforce, SharePoint, etc) and instead an **About** section is displayed.

For example: 
![image](https://github.com/oxygenxml/web-author-sample-plugins/assets/12260013/91736400-39e9-493c-8506-3714fba6bb4e)

**Comment by reifsnid** [comment]
On further investigation in the impose ditamap plugin, it appears that the getDitaContext() method that this plugin uses has been marked as experimental in the JavaScript API documentation:

https://www.oxygenxml.com/maven/com/oxygenxml/oxygen-webapp/25.1.0.0/jsdoc/sync.api.EditingContextManager.html#getDitaContext__anchor

> EXPERIMENTAL - Subject to change
Please note that this API is not marked as final and it can change in one of the next versions of the application. If you have suggestions, comments about it, please let us know.

Has this method and the other DitaContext methods been changed/removed in v26?

**Comment by derilu** [comment]
Hello,

We thank you for the reported error.
We have fixed the issue in the code of the plugin. It is necessary to download it again [1], and you can use it in Web Author.
This fix did not involve the getDitaContext() method (that is no longer experimental); additionally, we will rectify it so that it no longer appears as ''experimental" in the documentation.

[1] https://github.com/oxygenxml/web-author-sample-plugins/tree/master

Best Regards,
Cosmin
